feat: [sc-15957] Implement degree.md in api documentation
Cyber4All/competency-ecosystem-docs pull request #20
Opened 2022-12-19 20:50 UTC by AStoerkel1

Story details: https://app.shortcut.com/clarkcan/story/15957

![image](https://user-images.githubusercontent.com/41537999/208520922-1e5cd7fa-f109-4e30-bb9d-5e3629fb8f25.png)

2022-12-20 19:51 UTC, pmanal1 approved these changes

2022-12-22 16:52 UTC, Cwagne17 requested changes

2022-12-22 16:52 UTC, Cwagne17 commented on docs/competency-api/degree.md
> +### Description
Needs a description

2022-12-22 16:52 UTC, Cwagne17 commented on docs/competency-api/degree.md
> +{
Can we have a curl request example after postman is formatted.

2022-12-23 14:14 UTC, JosueMolinaMorales commented on docs/competency-api/degree.md
> +# Degree
I noticed you don't have a note about headers here. Can you add that?

2022-12-23 14:15 UTC, JosueMolinaMorales reviewed
Looks good. Just chris's comments and something i left.

2023-01-04 19:24 UTC, JosueMolinaMorales approved these changes

2023-01-05 17:31 UTC, shanioffe approved these changes
Looks good

2023-01-09 13:13 UTC, mfranz1 requested changes

2023-01-09 13:13 UTC, mfranz1 commented on docs/competency-api/degree.md
> +| 400 | Competency is deprecated, rejected, or published and cannot be updated. Or body is incorrectly formatted. |
Can it be made more obvious that this is a list of 400 errors

2023-01-09 16:22 UTC, Cwagne17 approved these changes

2023-01-09 16:55 UTC, mfranz1 approved these changes

2023-01-09 17:11 UTC, merged