implement notes.md for competencies
Cyber4All/competency-ecosystem-docs pull request #23
Opened 2023-01-03 21:11 UTC by shanioffe

2023-01-04 15:11 UTC, AStoerkel1 requested changes

2023-01-04 15:11 UTC, AStoerkel1 commented on docs/competency-api/notes.md
> +  -L "https://api.competency-constructor.clark.center/competencies/6112745b84804cf5833aa94c/behavior"
```suggestion
  -L "https://api.competency-constructor.clark.center/competencies/6112745b84804cf5833aa94c/notes"
```

2023-01-04 19:31 UTC, JosueMolinaMorales requested changes

2023-01-04 19:31 UTC, JosueMolinaMorales commented on docs/competency-api/notes.md
> +| notes | false | string | Any notes related to the competency |
```suggestion
| details | true | string | Any notes related to the competency |
```
`notes` is actually `details` and it is required

2023-01-04 19:31 UTC, JosueMolinaMorales commented on docs/competency-api/notes.md
> +        notes: "This competency is meant for students with a Cyber Security track only."
```suggestion
        details: "This competency is meant for students with a Cyber Security track only."
```

2023-01-04 19:31 UTC, JosueMolinaMorales commented on docs/competency-api/notes.md
> +        notes: "This competency is meant for students with a Cyber Security track only."
```suggestion
        details: "This competency is meant for students with a Cyber Security track only."
```

2023-01-05 17:21 UTC, pmanal1 approved these changes

2023-01-06 14:55 UTC, JosueMolinaMorales approved these changes

2023-01-06 17:07 UTC, pzalep1 approved these changes

2023-01-09 13:16 UTC, mfranz1 requested changes

2023-01-09 13:16 UTC, mfranz1 commented on docs/competency-api/notes.md
> +| 400 | Competency is deprecated, rejected, or published and cannot be updated. Or body is incorrectly formatted. |
I left this comment on Andy's and Paige's PRs but Can it be made more obvious that this is a list of 400 errors?

2023-01-09 16:18 UTC, Cwagne17 approved these changes

2023-01-11 13:58 UTC, mfranz1 requested changes
The competency.md I believe has it's own story. It should not be apart of this PR

2023-01-17 14:01 UTC, mfranz1 approved these changes

2023-01-17 17:44 UTC, AStoerkel1 approved these changes

2023-01-17 17:45 UTC, merged